# -*- coding: utf-8 -*-
"""DATA-301-Hello-World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhQUzvKfQCwGnB0ca8g58b3ZzP_mQAxX
"""

a = 10
b = 10

a+b